// This file is autogenerated by VESC Tool

#ifndef CONF_DEFAULT_H_
#define CONF_DEFAULT_H_

// Level 0 Pitch Kp
#ifndef APPCONF_TNT_KP0
#define APPCONF_TNT_KP0 5
#endif

// Level 1 Pitch Kp
#ifndef APPCONF_TNT_KP1
#define APPCONF_TNT_KP1 20
#endif

// Level 2 Pitch Kp
#ifndef APPCONF_TNT_KP2
#define APPCONF_TNT_KP2 0
#endif

// Level 3 Pitch Kp
#ifndef APPCONF_TNT_KP3
#define APPCONF_TNT_KP3 0
#endif

// Level 4 Pitch Kp
#ifndef APPCONF_TNT_KP4
#define APPCONF_TNT_KP4 0
#endif

// Level 1 Pitch Kp Angle
#ifndef APPCONF_TNT_PITCH1
#define APPCONF_TNT_PITCH1 1
#endif

// Level 2 Pitch Kp Angle
#ifndef APPCONF_TNT_PITCH2
#define APPCONF_TNT_PITCH2 0
#endif

// Level 3 Pitch Kp Angle
#ifndef APPCONF_TNT_PITCH3
#define APPCONF_TNT_PITCH3 0
#endif

// Level 4 Pitch Kp Angle
#ifndef APPCONF_TNT_PITCH4
#define APPCONF_TNT_PITCH4 0
#endif

// Mahony KP
#ifndef APPCONF_TNT_MAHONY_KP
#define APPCONF_TNT_MAHONY_KP 2
#endif

// Kp Rate
#ifndef APPCONF_TNT_KP_RATE
#define APPCONF_TNT_KP_RATE 0.5
#endif

// Kalman Factor 1
#ifndef APPCONF_TNT_KALMAN_Q1
#define APPCONF_TNT_KALMAN_Q1 0.0047
#endif

// Kalman Factor 2
#ifndef APPCONF_TNT_KALMAN_Q2
#define APPCONF_TNT_KALMAN_Q2 0.08
#endif

// Kalman Factor 3
#ifndef APPCONF_TNT_KALMAN_THETA
#define APPCONF_TNT_KALMAN_THETA 0.9
#endif

// Level 1 Roll Kp
#ifndef APPCONF_TNT_ROLL_KP1
#define APPCONF_TNT_ROLL_KP1 0
#endif

// Level 2 Roll Kp
#ifndef APPCONF_TNT_ROLL_KP2
#define APPCONF_TNT_ROLL_KP2 0.3
#endif

// Level 3 Roll Kp
#ifndef APPCONF_TNT_ROLL_KP3
#define APPCONF_TNT_ROLL_KP3 0
#endif

// Level 1 Roll Kp Angle
#ifndef APPCONF_TNT_ROLL1
#define APPCONF_TNT_ROLL1 5
#endif

// Level 2 Roll Kp Angle
#ifndef APPCONF_TNT_ROLL2
#define APPCONF_TNT_ROLL2 10
#endif

// Level 3 Roll Kp Angle
#ifndef APPCONF_TNT_ROLL3
#define APPCONF_TNT_ROLL3 0
#endif

// Level 1 Roll Kp Braking
#ifndef APPCONF_TNT_BRKROLL_KP1
#define APPCONF_TNT_BRKROLL_KP1 0
#endif

// Level 2 Roll Kp Braking
#ifndef APPCONF_TNT_BRKROLL_KP2
#define APPCONF_TNT_BRKROLL_KP2 0.3
#endif

// Level 3 Roll Kp Braking
#ifndef APPCONF_TNT_BRKROLL_KP3
#define APPCONF_TNT_BRKROLL_KP3 0
#endif

// Level 1 Roll Kp Angle Braking
#ifndef APPCONF_TNT_BRKROLL1
#define APPCONF_TNT_BRKROLL1 5
#endif

// Level 2 Roll Kp Angle Braking
#ifndef APPCONF_TNT_BRKROLL2
#define APPCONF_TNT_BRKROLL2 10
#endif

// Level 3 Roll Kp Angle Braking
#ifndef APPCONF_TNT_BRKROLL3
#define APPCONF_TNT_BRKROLL3 0
#endif

// Loop Hertz
#ifndef APPCONF_TNT_HERTZ
#define APPCONF_TNT_HERTZ 832
#endif

// Pitch Axis Fault Cutoff
#ifndef APPCONF_TNT_FAULT_PITCH
#define APPCONF_TNT_FAULT_PITCH 90
#endif

// Roll Axis Fault Cutoff
#ifndef APPCONF_TNT_FAULT_ROLL
#define APPCONF_TNT_FAULT_ROLL 90
#endif

// ADC1 Switch Voltage
#ifndef APPCONF_TNT_FAULT_ADC1
#define APPCONF_TNT_FAULT_ADC1 3
#endif

// ADC2 Switch Voltage
#ifndef APPCONF_TNT_FAULT_ADC2
#define APPCONF_TNT_FAULT_ADC2 3
#endif

// Beep on Sensor Fault
#ifndef APPCONF_TNT_IS_FOOTBUZZ_ENABLED
#define APPCONF_TNT_IS_FOOTBUZZ_ENABLED 1
#endif

// Pitch Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_PITCH
#define APPCONF_TNT_FAULT_DELAY_PITCH 1000
#endif

// Roll Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_ROLL
#define APPCONF_TNT_FAULT_DELAY_ROLL 1000
#endif

// Half Switch Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_SWITCH_HALF
#define APPCONF_TNT_FAULT_DELAY_SWITCH_HALF 250
#endif

// Full Switch Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_SWITCH_FULL
#define APPCONF_TNT_FAULT_DELAY_SWITCH_FULL 250
#endif

// ADC Half State Fault ERPM
#ifndef APPCONF_TNT_FAULT_ADC_HALF_ERPM
#define APPCONF_TNT_FAULT_ADC_HALF_ERPM 300
#endif

// Treat Both Sensors as One (Posi)
#ifndef APPCONF_TNT_FAULT_IS_DUAL_SWITCH
#define APPCONF_TNT_FAULT_IS_DUAL_SWITCH 0
#endif

// Disable Moving Faults
#ifndef APPCONF_TNT_FAULT_MOVING_FAULT_DISABLED
#define APPCONF_TNT_FAULT_MOVING_FAULT_DISABLED 0
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_DUTY_ANGLE
#define APPCONF_TNT_TILTBACK_DUTY_ANGLE 5
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_DUTY_SPEED
#define APPCONF_TNT_TILTBACK_DUTY_SPEED 3
#endif

// Duty Cycle
#ifndef APPCONF_TNT_TILTBACK_DUTY
#define APPCONF_TNT_TILTBACK_DUTY 0.8
#endif

// Beep on Duty Tiltback
#ifndef APPCONF_TNT_IS_DUTYBUZZ_ENABLED
#define APPCONF_TNT_IS_DUTYBUZZ_ENABLED 0
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_HV_ANGLE
#define APPCONF_TNT_TILTBACK_HV_ANGLE 8
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_HV_SPEED
#define APPCONF_TNT_TILTBACK_HV_SPEED 1
#endif

// High Voltage Threshold
#ifndef APPCONF_TNT_TILTBACK_HV
#define APPCONF_TNT_TILTBACK_HV 64.5
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_LV_ANGLE
#define APPCONF_TNT_TILTBACK_LV_ANGLE 10
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_LV_SPEED
#define APPCONF_TNT_TILTBACK_LV_SPEED 1
#endif

// Low Voltage Threshold
#ifndef APPCONF_TNT_TILTBACK_LV
#define APPCONF_TNT_TILTBACK_LV 45
#endif

// Return To Level Speed
#ifndef APPCONF_TNT_TILTBACK_RETURN_SPEED
#define APPCONF_TNT_TILTBACK_RETURN_SPEED 5
#endif

// Constant Tiltback
#ifndef APPCONF_TNT_TILTBACK_CONSTANT
#define APPCONF_TNT_TILTBACK_CONSTANT 0
#endif

// Constant Tiltback ERPM
#ifndef APPCONF_TNT_TILTBACK_CONSTANT_ERPM
#define APPCONF_TNT_TILTBACK_CONSTANT_ERPM 500
#endif

// Nose Angling Speed
#ifndef APPCONF_TNT_NOSEANGLING_SPEED
#define APPCONF_TNT_NOSEANGLING_SPEED 5
#endif

// Remote Type
#ifndef APPCONF_TNT_INPUTTILT_REMOTE_TYPE
#define APPCONF_TNT_INPUTTILT_REMOTE_TYPE 0
#endif

// Tiltback Angle Limit
#ifndef APPCONF_TNT_INPUTTILT_ANGLE_LIMIT
#define APPCONF_TNT_INPUTTILT_ANGLE_LIMIT 10
#endif

// Tiltback Speed
#ifndef APPCONF_TNT_INPUTTILT_SPEED
#define APPCONF_TNT_INPUTTILT_SPEED 25
#endif

// Tiltback Smoothing Factor
#ifndef APPCONF_TNT_INPUTTILT_SMOOTHING_FACTOR
#define APPCONF_TNT_INPUTTILT_SMOOTHING_FACTOR 1
#endif

// Invert Throttle
#ifndef APPCONF_TNT_INPUTTILT_INVERT_THROTTLE
#define APPCONF_TNT_INPUTTILT_INVERT_THROTTLE 1
#endif

// Input Deadband
#ifndef APPCONF_TNT_INPUTTILT_DEADBAND
#define APPCONF_TNT_INPUTTILT_DEADBAND 0.1
#endif

// Sticky Tilt Angle 1
#ifndef APPCONF_TNT_STICKYTILT_VAL1
#define APPCONF_TNT_STICKYTILT_VAL1 3
#endif

// Sticky Tilt Angle 2
#ifndef APPCONF_TNT_STICKYTILT_VAL2
#define APPCONF_TNT_STICKYTILT_VAL2 6
#endif

// Enable Stickytilt
#ifndef APPCONF_TNT_IS_STICKYTILT_ENABLED
#define APPCONF_TNT_IS_STICKYTILT_ENABLED 1
#endif

// Startup Pitch Axis Angle Tolerance
#ifndef APPCONF_TNT_STARTUP_PITCH_TOLERANCE
#define APPCONF_TNT_STARTUP_PITCH_TOLERANCE 5
#endif

// Startup Roll Axis Angle Tolerance
#ifndef APPCONF_TNT_STARTUP_ROLL_TOLERANCE
#define APPCONF_TNT_STARTUP_ROLL_TOLERANCE 45
#endif

// Startup Centering Speed
#ifndef APPCONF_TNT_STARTUP_SPEED
#define APPCONF_TNT_STARTUP_SPEED 60
#endif

// Startup Click Current
#ifndef APPCONF_TNT_STARTUP_CLICK_CURRENT
#define APPCONF_TNT_STARTUP_CLICK_CURRENT 0
#endif

// Enable Simple Start
#ifndef APPCONF_SIMPLESTART_ENABLED
#define APPCONF_SIMPLESTART_ENABLED 0
#endif

// Enable Push Start
#ifndef APPCONF_PUSHSTART_ENABLED
#define APPCONF_PUSHSTART_ENABLED 0
#endif

// Enable Dirty Landings
#ifndef APPCONF_DIRTYLANDINGS_ENABLED
#define APPCONF_DIRTYLANDINGS_ENABLED 0
#endif

// Brake Current
#ifndef APPCONF_TNT_BRAKE_CURRENT
#define APPCONF_TNT_BRAKE_CURRENT 6
#endif

// Enable Buzzer on Servo/PPM
#ifndef APPCONF_TNT_IS_BUZZER_ENABLED
#define APPCONF_TNT_IS_BUZZER_ENABLED 0
#endif

// Disable Package
#ifndef APPCONF_TNT_DISABLE
#define APPCONF_TNT_DISABLE 0
#endif

// Package Version
#ifndef APPCONF_TNT_VERSION
#define APPCONF_TNT_VERSION 1
#endif

// CONF_DEFAULT_H_
#endif

